version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=Zu8cMlH3r44s8c1N0j1tJ0zBWIzrHHx2JJvQsyudazN7LUFsubttzEc5Zgf4cLXWDi
      - DEBUG=1

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: